[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
commands = [
  "python -m venv --copies /opt/venv && . /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.build]
commands = []

[phases.start]
cmd = "/opt/venv/bin/python hookahBOT.py"
